[package]
name = "ctap-types"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
cbor-smol = "0.4"
cosey = "0.3"
delog = "0.1"
heapless = { version = "0.7", default-features = false, features = ["serde"] }
heapless-bytes = "0.3"
interchange = "0.2.1"
serde = { version = "1", default-features = false, features = ["derive"] }
serde-indexed = "0.1"
serde_repr = "0.1"

# iso7816 = { git = "https://github.com/ycrypto/iso7816" }
iso7816 = "0.1.0-alpha.1"

[features]
log-all = ["cbor-smol/log-all"]
log-none = []

# [patch.crates-io]
# heapless = { git = "https://github.com/nickray/heapless", branch = "bytebuf-0.5.6" }
